export const orgInforamtionData: any = {
    "calixOrganization": {
        "createTime": "2020-10-14T07:47:10.282",
        "updateTime": "2020-10-14T07:47:10.282",
        "id": "12847872",
        "name": "siva",
        "description": "123 testing",
        "externalOrgRef": null,
        "salesforceId": null,
        "oracleId": null,
        "parentId": null,
        "capStatus": null,
        "capOverride": null,
        "capExpires": null,
        "bypassCAP": false,
        "inheritList": null,
        "parentOrgName": null,
        "territory": null,
        "cloudGeography": null,
        "country": null,
        "apiQuota": "0"
    },
    "spId": "5G1ixiHzmu"
}

export const orgEntitlements: any = [
    {
        "createTime": "2021-03-26T09:37:03.813",
        "updateTime": "2022-02-24T07:13:44.939",
        "id": "8077181191213562552",
        "appType": 119,
        "name": "Marketing Cloud Service",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": "2020-11-01",
        "endDate": "2021-12-31",
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "About_to_Expire",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2021-03-26T09:37:05.062",
        "updateTime": "2022-02-17T07:08:04.787",
        "id": "8077181191213562802",
        "appType": 202,
        "name": "Samsung Smartthings Hub",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Expired",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2022-02-23T06:55:12.634",
        "updateTime": "2022-02-23T06:55:12.634",
        "id": "8077181191213778552",
        "appType": 207,
        "name": "Servify Bronze",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Active",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2022-02-24T07:13:41.116",
        "updateTime": "2022-02-24T07:13:41.116",
        "id": "8077181191213779452",
        "appType": 208,
        "name": "Calix Cloud Subscriber Service API",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "In_Grace_Period",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2022-02-24T07:18:48.229",
        "updateTime": "2022-02-24T07:18:48.229",
        "id": "8077181191213779502",
        "appType": 211,
        "name": "Broadband Performance Testing",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "In_Grace_Period",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2022-01-27T05:54:27.206",
        "updateTime": "2022-02-24T07:13:50.37",
        "id": "8077181191213760052",
        "appType": 206,
        "name": "ARLO",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Active",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2022-01-27T06:15:34.444",
        "updateTime": "2022-02-24T07:13:45.916",
        "id": "8077181191213760102",
        "appType": 131,
        "name": "Service Cloud Performance Testing",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "About_to_Expire",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2021-03-26T09:37:04.562",
        "updateTime": "2022-02-17T07:08:03.867",
        "id": "8077181191213562702",
        "appType": 200,
        "name": "EXOS Framework",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Expired",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2021-03-26T09:37:05.565",
        "updateTime": "2022-02-17T07:08:06.217",
        "id": "8077181191213562902",
        "appType": 204,
        "name": "ExperienceIQ",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Expired",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2021-03-26T09:37:05.305",
        "updateTime": "2022-02-24T07:13:47.744",
        "id": "8077181191213562852",
        "appType": 203,
        "name": "ProtectIQ",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Active",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2022-02-16T16:48:53.169",
        "updateTime": "2022-02-24T14:54:23.93",
        "id": "8077181191213769552",
        "appType": 120,
        "name": "Service Cloud Basic",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Expired",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2020-10-14T07:55:42.416",
        "updateTime": "2022-02-17T07:08:06.677",
        "id": "58305661",
        "appType": 205,
        "name": "ExperienceIQ And ProtectIQ",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Expired",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2021-04-29T07:29:39.11",
        "updateTime": "2022-02-24T07:13:45.455",
        "id": "8077181191213571452",
        "appType": 122,
        "name": "Marketing Cloud Platform",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "About_to_Expire",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2021-10-20T06:26:08.038",
        "updateTime": "2022-06-16T03:41:15.018",
        "id": "8077181191213711602",
        "appType": 102,
        "name": "Calix Operations Cloud",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "About_to_Expire",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2020-10-22T22:33:45.937",
        "updateTime": "2022-02-17T07:08:04.331",
        "id": "8077181191213532702",
        "appType": 201,
        "name": "EXOS Support",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Expired",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2021-12-01T05:05:07.488",
        "updateTime": "2022-03-07T08:54:17.396",
        "id": "8077181191213730002",
        "appType": 118,
        "name": "Service Cloud",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Active",
        "serviceName": null,
        "serviceEdition": null
    },
    {
        "createTime": "2021-12-01T05:05:07.796",
        "updateTime": "2022-09-08T12:22:47.655",
        "id": "8077181191213730052",
        "appType": 209,
        "name": "Calix Marketing Cloud Plus",
        "entitlement": 100,
        "disabledFlag": false,
        "startDate": null,
        "endDate": null,
        "overrideEndDate": "",
        "contractNumber": null,
        "productFamily": null,
        "partCategory": null,
        "partNumber": null,
        "partDescription": null,
        "qty": null,
        "customer": null,
        "organizationId": "12847872",
        "status": "Expired",
        "serviceName": null,
        "serviceEdition": null
    }
]

export const errorStatus401OrgInfo: any = {
    "status": 401,
    "statusText": "Unauthorized User",
    "ok": false,
    "name": "HttpErrorResponse",
    "error": "User Unathorized"
}

export const errorStatus500OrgInfo: any = {
    "timestamp": "2022-09-27T07:53:19.771+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Java heap space",
    "path": "/api/v1"
}