export const wifiExtenderMockData: any = {
    "channel_bandwidth":"80MHz",
    "current":{
    "channel":60,
    "uoc_channel_number":13,
    "power":12,
    "coc_channel_number":9
    },
    "ranking_list":[
    {
    "channel":149,
    "uoc_channel_number":9,
    "power":-8.66,
    "coc_channel_number":2
    },
    {
    "channel":36,
    "uoc_channel_number":15,
    "power":14.57,
    "coc_channel_number":7
    }
    ],
    "recommend":{
    "channel":149,
    "uoc_channel_number":9,
    "power":-8.66,
    "coc_channel_number":2
    },
    "ranking":-1
}

export const wifiBackhaulMockData: any = {
    "HostName":"CXNK00E58240",
    "Name":"SAT 2037",
    "Wifi-score":5,
    "Avg-Wifi-score":5,
    "Signal-strength":-28,
    "SNR":67,
    "Airtime-usage":0,
    "DS-phy-rate":999098,
    "US-phy-rate":1036304,
    "DS-packet-drops":0,
    "DS-retx-packets":826,
    "MACAddress":"f8:85:f9:29:0b:52",
    "Connection-type":"WiFi",
    "SSID":"Calix-5G-backhaulE5CCA8",
    "Mode":"11ax",
    "AccessPoint":"CXNK00E5CCA8",
    "AccessPointHostName":"Router",
    "Band":"5",
    "Channel-number":132,
    "satPlacementRating":11,
    "client-efficiency-score":0.8322
    }